{"uuid": "13baf1da-a44f-4493-8ffb-c9b2ac7517f0", "children": ["eacf08b1-32a6-49a7-ac87-2a0ea01e74be", "351801a6-379f-42b8-977e-364b0935aff1", "944f0fdb-d2d0-4f4b-9568-8ce8eef693ef", "186a3b6c-e84a-4068-b25f-b9d60d3f3628"], "befores": [{"name": "Driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=87.0.4280.66)\n\n", "trace": "  File \"D:\\Anaconda3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"D:\\Git\\PycharmProjects\\PycharmProjects\\Reptile\\Web_Framework-master\\TestCases\\conftest.py\", line 20, in Driver\n    driver.maximize_window()\n  File \"D:\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 737, in maximize_window\n    self.execute(command, params)\n  File \"D:\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1610622166008, "stop": 1610622178681}], "start": 1610622166008, "stop": 1610622179039}