{"uuid": "34f99452-3d58-4449-b7bb-c04664208125", "children": ["0a2eda7f-c8b7-41e0-906f-0b79752c4cdc", "98bae66d-47d5-4cc9-98de-797b16844d21", "1ae57440-d19d-4764-a219-f9a8db066ac8", "dd14245e-b6ed-44ac-b726-4b618105c8d3"], "befores": [{"name": "Driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=87.0.4280.66)\n\n", "trace": "  File \"D:\\Anaconda3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"D:\\Git\\PycharmProjects\\PycharmProjects\\Reptile\\Web_Framework-master\\TestCases\\conftest.py\", line 18, in Driver\n    driver.maximize_window()\n  File \"D:\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 737, in maximize_window\n    self.execute(command, params)\n  File \"D:\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1610620278929, "stop": 1610620292731}], "start": 1610620278929, "stop": 1610620293181}