{"uuid": "377c077e-d74e-4f27-bdaf-bf67763fd10a", "children": ["ee90c911-b2de-4e88-aa2a-18bc292aaa0c", "ca88047a-2e9b-40fb-8db1-6cdde09f4f37", "985d3448-8b76-4171-9836-6cb7aea80814", "f7a5f765-99ba-4156-9a62-e86bd681d828"], "befores": [{"name": "Driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=87.0.4280.66)\n\n", "trace": "  File \"D:\\Anaconda3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"D:\\Git\\PycharmProjects\\PycharmProjects\\Reptile\\Web_Framework-master\\TestCases\\conftest.py\", line 18, in Driver\n    driver.maximize_window()\n  File \"D:\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 737, in maximize_window\n    self.execute(command, params)\n  File \"D:\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1610617395722, "stop": 1610617408322}], "start": 1610617395722, "stop": 1610617408775}